/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_carlosbonilla;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.DefaultMutableTreeNode;
/**
 *
 * @author lospe
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        mainmenu.setVisible(true);
        trans.setVisible(false);
        CreatePlayer.setVisible(false);
        panelCrearEquipo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearequipo = new javax.swing.JFrame();
        panelCrearEquipo = new javax.swing.JPanel();
        btn_addTeam = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_equipoNombre = new javax.swing.JTextField();
        tf_equipoPais = new javax.swing.JTextField();
        tf_equipoCiudad = new javax.swing.JTextField();
        tf_equipoEstadio = new javax.swing.JTextField();
        equipoLogout = new javax.swing.JButton();
        transferir = new javax.swing.JFrame();
        trans = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolLiga = new javax.swing.JTree();
        btn_transferir = new javax.swing.JButton();
        crearplayer = new javax.swing.JFrame();
        CreatePlayer = new javax.swing.JPanel();
        edad = new javax.swing.JSpinner();
        posicion = new javax.swing.JComboBox<>();
        btn_addplayer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        mainmenu = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_equipo = new javax.swing.JButton();
        btn_crearplayer = new javax.swing.JButton();
        btn_trans = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        panelCrearEquipo.setBackground(new java.awt.Color(0, 0, 255));

        btn_addTeam.setText("Agregar");
        btn_addTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addTeamActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("pais");

        jLabel6.setText("estadio");

        jLabel7.setText("ciudad");

        tf_equipoCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_equipoCiudadActionPerformed(evt);
            }
        });

        tf_equipoEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_equipoEstadioActionPerformed(evt);
            }
        });

        equipoLogout.setText("salir");
        equipoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearEquipoLayout = new javax.swing.GroupLayout(panelCrearEquipo);
        panelCrearEquipo.setLayout(panelCrearEquipoLayout);
        panelCrearEquipoLayout.setHorizontalGroup(
            panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearEquipoLayout.createSequentialGroup()
                .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearEquipoLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_equipoEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_equipoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_equipoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_equipoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCrearEquipoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btn_addTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearEquipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(equipoLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelCrearEquipoLayout.setVerticalGroup(
            panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearEquipoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(equipoLogout)
                .addGap(32, 32, 32)
                .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_equipoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_equipoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_equipoCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_equipoEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addTeam)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout crearequipoLayout = new javax.swing.GroupLayout(crearequipo.getContentPane());
        crearequipo.getContentPane().setLayout(crearequipoLayout);
        crearequipoLayout.setHorizontalGroup(
            crearequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
            .addGroup(crearequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearequipoLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(panelCrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        crearequipoLayout.setVerticalGroup(
            crearequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(crearequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearequipoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        transferir.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(playerList);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Liga");
        arbolLiga.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(arbolLiga);

        btn_transferir.setText("Transferir Jugador");

        javax.swing.GroupLayout transLayout = new javax.swing.GroupLayout(trans);
        trans.setLayout(transLayout);
        transLayout.setHorizontalGroup(
            transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_transferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        transLayout.setVerticalGroup(
            transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transLayout.createSequentialGroup()
                .addGroup(transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btn_transferir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(transLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        transferir.getContentPane().add(trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(-24, 90, 770, -1));

        edad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));

        posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delantero", "Mediocentrista", "Defensa", "Portero" }));
        posicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionActionPerformed(evt);
            }
        });

        btn_addplayer.setText("agregar  jugador");
        btn_addplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addplayerActionPerformed(evt);
            }
        });

        jLabel1.setText("nombre");

        jLabel2.setText("edad");

        jLabel3.setText("posicion");

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreatePlayerLayout = new javax.swing.GroupLayout(CreatePlayer);
        CreatePlayer.setLayout(CreatePlayerLayout);
        CreatePlayerLayout.setHorizontalGroup(
            CreatePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePlayerLayout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(CreatePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePlayerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePlayerLayout.createSequentialGroup()
                        .addGroup(CreatePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_addplayer)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CreatePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
        );
        CreatePlayerLayout.setVerticalGroup(
            CreatePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePlayerLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(CreatePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(CreatePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(80, 80, 80)
                .addGroup(CreatePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(58, 58, 58)
                .addComponent(btn_addplayer)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout crearplayerLayout = new javax.swing.GroupLayout(crearplayer.getContentPane());
        crearplayer.getContentPane().setLayout(crearplayerLayout);
        crearplayerLayout.setHorizontalGroup(
            crearplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(crearplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearplayerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CreatePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        crearplayerLayout.setVerticalGroup(
            crearplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(crearplayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearplayerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CreatePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_equipo.setText("Crear equipo");
        btn_equipo.setFocusable(false);
        btn_equipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_equipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equipoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_equipo);

        btn_crearplayer.setText("Crear Jugador");
        btn_crearplayer.setFocusable(false);
        btn_crearplayer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_crearplayer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_crearplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearplayerActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_crearplayer);

        btn_trans.setText("Transferencia");
        btn_trans.setFocusable(false);
        btn_trans.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_trans.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_trans);

        javax.swing.GroupLayout mainmenuLayout = new javax.swing.GroupLayout(mainmenu);
        mainmenu.setLayout(mainmenuLayout);
        mainmenuLayout.setHorizontalGroup(
            mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenuLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 459, Short.MAX_VALUE))
        );
        mainmenuLayout.setVerticalGroup(
            mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenuLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 435, Short.MAX_VALUE))
        );

        jMenu1.setText("opciones");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearplayerActionPerformed
        this.setVisible(false);
        crearplayer.pack();
        crearplayer.setResizable(false);
        crearplayer.setVisible(true);
    }//GEN-LAST:event_btn_crearplayerActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void posicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicionActionPerformed

    private void tf_equipoEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_equipoEstadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_equipoEstadioActionPerformed

    private void tf_equipoCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_equipoCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_equipoCiudadActionPerformed

    private void btn_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equipoActionPerformed
       
        crearequipo.pack();
        crearequipo.setResizable(false);
        crearequipo.setVisible(true);
        panelCrearEquipo.setVisible(true);
        crearplayer.setVisible(false);    }//GEN-LAST:event_btn_equipoActionPerformed

    private void btn_addplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addplayerActionPerformed
        if (Nombre.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el jugador");
        }else{
         DefaultListModel modelo= new DefaultListModel();
         modelo=(DefaultListModel) playerList.getModel();
         modelo.addElement(new Player((Integer)(edad.getValue()), Nombre.getText(), posicion.getSelectedItem().toString()));
         playerList.setModel(modelo);
        }
        
    }//GEN-LAST:event_btn_addplayerActionPerformed

    private void btn_addTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addTeamActionPerformed
        if(tf_equipoNombre.getText().isEmpty()||tf_equipoCiudad.getText().isEmpty()||tf_equipoEstadio.getText().isEmpty()||tf_equipoPais.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Porfavor llenar todos los espacios");
        }else{
            DefaultTreeModel m= (DefaultTreeModel)arbolLiga.getModel();
            DefaultMutableTreeNode r=(DefaultMutableTreeNode)m.getRoot();
            equipo e=new equipo(tf_equipoNombre.getText(),tf_equipoCiudad.getText(),tf_equipoPais.getText(),tf_equipoEstadio.getText());
            for (int i = 0; i < r.getChildCount(); i++) {
                DefaultMutableTreeNode nodoPais = (DefaultMutableTreeNode) r.getChildAt(i);
                if (nodoPais.getUserObject().equals(e.getNation())) {
                    DefaultMutableTreeNode nodoEquipo= new DefaultMutableTreeNode(e);
                    ((DefaultMutableTreeNode) r.getChildAt(i)).add(nodoEquipo);
                    
                } else if (i == r.getChildCount() - 1) {
                    DefaultMutableTreeNode nodocountry = new DefaultMutableTreeNode(e.getNation());
                        DefaultMutableTreeNode nodoEquipo = new DefaultMutableTreeNode(e);
                        nodocountry.add(nodoEquipo);
                        r.add(nodocountry);
                        ((DefaultMutableTreeNode) r.getChildAt(i+1)).add(nodoEquipo);
                    
                }

            }
            
            m.reload(r);
            arbolLiga.setModel(m);
            ((DefaultTreeModel)arbolLiga.getModel()).reload();
            tf_equipoCiudad.setText("");
            tf_equipoEstadio.setText("");
            tf_equipoNombre.setText("");
            tf_equipoPais.setText("");
            
        }

    }//GEN-LAST:event_btn_addTeamActionPerformed

    private void equipoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoLogoutActionPerformed
        
        crearequipo.setVisible(false);
        
        mainmenu.setVisible(true);
    }//GEN-LAST:event_equipoLogoutActionPerformed

    private void btn_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transActionPerformed
       transferir.pack();
       transferir.setResizable(false);
       transferir.setVisible(true);
        trans.setVisible(true);
    }//GEN-LAST:event_btn_transActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreatePlayer;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTree arbolLiga;
    private javax.swing.JButton btn_addTeam;
    private javax.swing.JButton btn_addplayer;
    private javax.swing.JButton btn_crearplayer;
    private javax.swing.JButton btn_equipo;
    private javax.swing.JButton btn_trans;
    private javax.swing.JButton btn_transferir;
    private javax.swing.JFrame crearequipo;
    private javax.swing.JFrame crearplayer;
    private javax.swing.JSpinner edad;
    private javax.swing.JButton equipoLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel mainmenu;
    private javax.swing.JPanel panelCrearEquipo;
    private javax.swing.JList<String> playerList;
    private javax.swing.JComboBox<String> posicion;
    private javax.swing.JTextField tf_equipoCiudad;
    private javax.swing.JTextField tf_equipoEstadio;
    private javax.swing.JTextField tf_equipoNombre;
    private javax.swing.JTextField tf_equipoPais;
    private javax.swing.JPanel trans;
    private javax.swing.JFrame transferir;
    // End of variables declaration//GEN-END:variables
}
